Repository Devil-Scout/DevilScout, pull requests merged in 2025-01, with the labels that each got.

#7 Add navigation bar
  lib/appwrapper.dart
  lib/main.dart
  lib/navigation/analyze_page_nav.dart
  lib/navigation/home_page_nav.dart
  lib/navigation/manage_page_nav.dart
  lib/navigation/scout_page_nav.dart
  lib/pages/analyze/analyze_home.dart
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/pages/auth/login_select.dart
  lib/pages/home/home.dart
  lib/pages/manage/manage_home.dart
  lib/pages/scout/scout_home.dart
  lib/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, ui/ux

#8 Prefer relative imports
  analysis_options.yaml
Labels: code style

#9 Import cleanup
  lib/appwrapper.dart
  lib/main.dart
  lib/navigation/analyze_page_nav.dart
  lib/navigation/home_page_nav.dart
  lib/navigation/manage_page_nav.dart
  lib/navigation/scout_page_nav.dart
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/pages/auth/login_select.dart
  lib/pages/manage/manage_home.dart
  lib/pages/scout/scout_home.dart
Labels: code style

#3 Login logic
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/org/devilscout/client_android/MainActivity.kt
  ios/.gitignore
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/components/labeled_text_field.dart
  lib/main.dart
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/pages/auth/login_select.dart
  lib/supabase/client.dart
  lib/supabase/email_auth.dart
  lib/supabase/sso_auth.dart
  pubspec.lock
  pubspec.yaml
Labels: dependencies, feature

#11 Improve nav bar styling
  lib/nav_bar.dart
  lib/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: dependencies, code style, ui/ux

#12 Implement client for Supabase backend
  .github/workflows/flutter-build.yml
  build.yaml
  lib/main.dart
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/pages/auth/login_select.dart
  lib/supabase/.gitignore
  lib/supabase/base/auth.dart
  lib/supabase/base/current_user.dart
  lib/supabase/client.dart
  lib/supabase/core/core.dart
  lib/supabase/core/team_requests.dart
  lib/supabase/core/team_users.dart
  lib/supabase/core/teams.dart
  lib/supabase/database.dart
  lib/supabase/email_auth.dart
  lib/supabase/frc/districts.dart
  lib/supabase/frc/events.dart
  lib/supabase/frc/frc.dart
  lib/supabase/frc/matches.dart
  lib/supabase/frc/seasons.dart
  lib/supabase/frc/teams.dart
  lib/supabase/scouting/questions.dart
  lib/supabase/scouting/scouting.dart
  lib/supabase/sso_auth.dart
  pubspec.lock
  pubspec.yaml
Labels: dependencies, feature

#17 Strict set of lints
  .github/workflows/dart-analyze.yml
  analysis_options.yaml
  lib/components/labeled_text_field.dart
  lib/main.dart
  lib/nav_bar.dart
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/pages/auth/login_select.dart
  lib/router.dart
  lib/supabase/base/auth.dart
  lib/supabase/core/team_requests.dart
  lib/supabase/database.dart
  lib/supabase/frc/districts.dart
  lib/supabase/frc/events.dart
  lib/supabase/frc/matches.dart
  lib/supabase/frc/seasons.dart
  lib/supabase/frc/teams.dart
  lib/supabase/scouting/questions.dart
  lib/theme.dart
  pubspec.yaml
Labels: code style

#18 Split GHA platform jobs for clarity
  .github/workflows/flutter-build.yml
Labels: code style
