Repository Devil-Scout/DevilScout, pull requests merged in 2025-02, with the labels that each got.

#21 Add join team page
  analysis_options.yaml
  devtools_options.yaml
  lib/components/full_screen_message.dart
  lib/components/searchable_text_field.dart
  lib/components/team_avatar.dart
  lib/components/team_card.dart
  lib/pages/scout/join_team.dart
  lib/pages/scout/scout_home.dart
  lib/router.dart
  lib/supabase/base/current_user.dart
  lib/supabase/core/core.dart
  lib/supabase/core/team_requests.dart
  lib/supabase/core/teams.dart
  lib/supabase/database.dart
  lib/supabase/frc/frc.dart
  lib/supabase/scouting/scouting.dart
  lib/theme.dart
Labels: feature, ui/ux

#19 Make login pages stateless
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/router.dart
Labels: performance

#22 Update dependencies
  pubspec.lock
  pubspec.yaml
Labels: dependencies

#26 Add basic settings tab
  android/.gitignore
  android/app/src/main/AndroidManifest.xml
  git/HEAD
  git/branches
  ios/Podfile.lock
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  lib/components/dialogs.dart
  lib/components/full_width.dart
  lib/components/labeled_text_field.dart
  lib/components/team_avatar.dart
  lib/components/team_card.dart
  lib/components/teams.dart
  lib/components/text_fields.dart
  lib/main.dart
  lib/pages/auth/email_login.dart
  lib/pages/auth/email_signup.dart
  lib/pages/auth/login_select.dart
  lib/pages/manage/manage_home.dart
  lib/pages/scout/scout_home.dart
  lib/pages/settings/edit_account.dart
  lib/pages/settings/join_team.dart
  lib/pages/settings/settings_home.dart
  lib/router.dart
  lib/supabase/base/auth.dart
  lib/supabase/base/current_user.dart
  lib/supabase/core/team_requests.dart
  lib/supabase/core/team_users.dart
  lib/supabase/core/teams.dart
  lib/supabase/database.dart
  lib/supabase/frc/districts.dart
  lib/supabase/frc/events.dart
  lib/supabase/frc/matches.dart
  lib/supabase/frc/seasons.dart
  lib/supabase/frc/teams.dart
  lib/supabase/scouting/questions.dart
  lib/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, ui/ux
